version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - todoApi-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: .
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  todoApi-db-volume:
